### PR TITLE
Dowgrade to Go 1.16

### PR DESCRIPTION
**Pull request by eloycoto**
This is because RPM build is not going to work on Fedora 35, that it's
the current branch and we need to run on top of that version.

Fedora 36 will have Golang 1.17.

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>

### CODE REVIEW

**Review by jakub-dzon — APPROVED** [review]

**Comment by machacekondra** [comment]
It's just a build time req, I think it's fine to use for dev, can we build f36 for build and re-build for 35/34?

**Comment by machacekondra** [comment]
> It's just a build time req, I think it's fine to use for dev, can we build f36 for build and re-build for 35/34?

Answering myself, that would not work I think, but maybe there is a way to do it.

**Comment by pkliczewski** [comment]
Fedora 36 is [scheduled](https://news.itsfoss.com/fedora-36-release-date-features/) to be released on 26th of April. There is 1.18 go rpm available. Maybe it makes sense to wait those 5 days and ask everyone to move?

**Comment by gciavarrini** [comment]
> Fedora 36 is [scheduled](https://news.itsfoss.com/fedora-36-release-date-features/) to be released on 26th of April. There is 1.18 go rpm available. Maybe it makes sense to wait those 5 days and ask everyone to move?

@eloycoto The code lgtm but I also like @pkliczew suggestion. Waiting 5 days to avoid do/undo/redo seems not that bad. Any drawbacks?

**Review by pkliczewski — APPROVED** [review]
@eloycoto has a point. There is no go 1.17/1.18 on rhel8 we would need to package it. Let's keep 1.16 for now before we move to fc36 and el9.

**Comment by eloycoto** [comment]
Should this get merged?

**Pull request merged**
