### PR TITLE
Build RPM per each PR for testing

### PR DESCRIPTION
**Pull request by machacekondra**
This commit add github workflow to build RPM per each PR for testing
purposes of the manual flotta-operator job.

Signed-off-by: Ondra Machacek <omachace@redhat.com>

### CODE REVIEW

**Comment by gabriel-farache** [comment]
The `VERSION` is not set per PR? If the default `VERSION` is used (as of now, 0.1.0) if/when there are multiple PR simultaneously, the RPM will erased each other, no?

**Comment by machacekondra** [comment]
> The `VERSION` is not set per PR? If the default `VERSION` is used (as of now, 0.1.0) if/when there are multiple PR simultaneously, the RPM will erased each other, no?

Actually this is used, just for artifacts, it's not published anywhere but inside github workflow job: https://github.com/project-flotta/flotta-device-worker/actions/runs/2377517423

You can later use that file to test the build either locally or by manual trigger of flotta-operator workflow.

**Comment by gabriel-farache** [comment]
> > The `VERSION` is not set per PR? If the default `VERSION` is used (as of now, 0.1.0) if/when there are multiple PR simultaneously, the RPM will erased each other, no?
> 
> Actually this is used, just for artifacts, it's not published anywhere but inside github workflow job: https://github.com/project-flotta/flotta-device-worker/actions/runs/2377517423
> 
> You can later use that file to test the build either locally or by manual trigger of flotta-operator workflow.

Ok so there will be manual actions to do further testing
\lgtm then :)

**Review by gabriel-farache — APPROVED** [review]

**Review by masayag — APPROVED** [review]

**Comment by machacekondra** [comment]
Yes, but locally you can just run `make rpm` in device-worker repo and then:
`FOCUS="YOUR_TEST_CASE" SKIP_TEST_IMAGE_PULL=true  TEST_RPM="/home/omachace/rpmbuild/RPMS/x86_64/flotta-agent-race-0.1.0-1.fc34.x86_64.rpm" make integration-test`
This will test the recent device-worker code with your operator's test cases.

**Comment by masayag** [comment]
> Yes, but locally you can just run `make rpm` in device-worker repo and then: `FOCUS="YOUR_TEST_CASE" SKIP_TEST_IMAGE_PULL=true TEST_RPM="/home/omachace/rpmbuild/RPMS/x86_64/flotta-agent-race-0.1.0-1.fc34.x86_64.rpm" make integration-test` This will test the recent device-worker code with your operator's test cases.

That's very useful for writing integration-test for code that wasn't merged into device-worker yet.
Pls add this example to https://project-flotta.io/documentation/latest/dev/guide.html

**Pull request merged**
