### PR TITLE
Bump _go_ version from 1.16.15 to 1.17.11 in github/workflows

### PR DESCRIPTION
**Pull request by tupyy**
Signed-off-by: Cosmin Tupangiu <cosmin@redhat.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
https://project-flotta.io/documentation/v0_1_0/dev/installation.html#device-installation

**Comment by tupyy** [comment]
Thanks. That's putting me in trouble. I've bumped the version of the operator because of the commit which adds the models for the host devices but the new version bumps also the k8s dependencies version. :)
Any ideas :)?

**Comment by eloycoto** [comment]
> Thanks. That's putting me in trouble. I've bumped the version of the operator because of the commit which adds the models for the host devices but the new version bumps also the k8s dependencies version. :)
> Any ideas :)?

So, for me two things: 

- Keep operator 1.16 compatible regarding apis/ and pkg, I think that was compatible. 
- Or move apis/ and pkg directories to another sub-project. 


I prefer the first one, but that it's a decision that needs to be taken at flotta-core meeting.

**Comment by tupyy** [comment]
no more relevant. we keep 1.16

**Pull request closed without merging**
